[project]
name = "golem-agent-sdk"
version = "0.1.1"
description = "Python SDK for Golem extensions"
readme = "README.md"
authors = [
    { name = "Nawaz Gafar" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
module-name = "golem"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
